import = [
    "~/work/alacritty-theme/themes/catppuccin_mocha.toml"
]
live_config_reload = true 

[window]
decorations = "Full"
opacity = 0.7
blur = true
startup_mode =  "Maximized"

[font]
normal = { family = "Cascadia Code NF", style="Regular" }
bold = { family = "Cascadia Code NF", style="Bold" }
size = 11

